### ISSUE TITLE
Added new button to Downloads Settings page

### ISSUE THREAD

**Issue by avsaponchik** [badanka/Compact#23]
11 August - Steam Client Beta Update

Added button to clear local cache under download settings. This may fix downloads by removing stale or corrupt cached data.

![default](https://cloud.githubusercontent.com/assets/1337953/17575094/17f582c8-5f6f-11e6-85d4-1a36cbf2e3ca.PNG)

**Comment by badanka** [comment]
I probably won't have time to get a beta out before the Steam beta goes final, but I'll have it fixed in the next update that I'm working on.

**Comment by badanka** [comment]
Fixed in 1.5.76
