### ISSUE TITLE
Most text unreadable on Linux

### ISSUE THREAD

**Issue by yaomtc** [badanka/Compact#26]
![screenshot_20161013_200223](https://cloud.githubusercontent.com/assets/5534045/19371337/1e65f244-9180-11e6-9888-a56540846fc0.png)

Using Arch Linux with Steam client version 1476379980.

**Comment by badanka** [comment]
Uh, shit. Don't know how that happened, I haven't changed anything regarding Linux as far as I'm aware. I'll have to look into that. No problems with 1.5.76?

**Comment by yaomtc** [comment]
I don't know, this is my first time in quite a while trying Steam Compact,
and might be my first time using it on Linux (used it on Windows
previously). I'll test it right now.

**Comment by badanka** [comment]
Have you followed the instructions in the **readme.txt** regarding installing the included fonts and changing the **settings.ini** file then?

**Comment by yaomtc** [comment]
Whoops, I did not. Fixed now. That's what I get for not RTFM.
