### ISSUE TITLE
bad folder structure for cloning

### ISSUE THREAD

**Issue by l0wBoB** [badanka/Compact#28]
Hey,
did you consider to change the folder structure so one can clone Compact directly to ..\Steam\skins via the GitHub desktop app?
Thank you for your work.

**Comment by badanka** [comment]
I'm not very good with GitHub so I hadn't really considered that. I would need it to be set in at least \Steam\ though so that Linux users can get the _fonts_ folder as well, would that work?

**Comment by l0wBoB** [comment]
It shouldn't make much of a difference for the end user where to find the fonts or additional files as they are to be executed/installed manually anyway.

Sometimes the competition can be a good inspiration: https://github.com/Outsetini/Air-for-Steam
If one clones that repo into the folder ..\Steam\skins, all the files are placed in the subfolder Air-for-Steam and can then be maintained via the app automatically.

**Comment by badanka** [comment]
True, that statement is proof that I shouldn't reply to stuff as soon as I've woken up. It made more sense then than it does now. I still have the problem with users not knowing where to place anything, but it could perhaps be remedied. I'll do something about it though.

But, I feel I have to get it on the record that I'm too old and have been maintaining this skin for too long to be trying to compete with anyone else.
