### ISSUE TITLE
Version number is wrong in UI

### ISSUE THREAD

**Issue by ssolidus** [badanka/Compact#30]
![image](https://cloud.githubusercontent.com/assets/14216632/25483522/91e70830-2b99-11e7-9091-80b2f450e366.png)

**Comment by badanka** [comment]
You might want to try to extract the contents of the .zip file once more, as it looks like you haven't gotten the latest files. As you can see [here](https://github.com/badanka/Compact/blob/master/resource/menus/steam.menu) the version number is correct in the latest file.
