### ISSUE TITLE
"Add a game" option missing from Library section

### ISSUE THREAD

**Issue by HairyMilkshakes** [badanka/Compact#32]
![2017-10-31_8-19-41](https://user-images.githubusercontent.com/13473043/32232130-9a25da2c-be14-11e7-9805-e1172e5dca3b.png)
Hi, your skin is missing the "add a game" option in the library tab. Please refer to attached images.
![2017-10-31_8-18-17](https://user-images.githubusercontent.com/13473043/32232122-90234da2-be14-11e7-820a-8b3873337ca8.png)

**Comment by badanka** [comment]
This is intentional since the options are already available in the **Games** menu. It was part of the job of removing Steam's "multiple ways of doing the same thing" method which in my mind is more confusing than beneficial.

**Comment by HairyMilkshakes** [comment]
Understood and I actually realized that about 30 minutes after I posted. Thanks a lot!
