### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ssolidus** [badanka/Compact#34]
Hi,

I get very high CPU usage from Steam using this theme, especially while in-game. It uses between 15%
 and 25%.

This is a recent development.

I am using the Steam beta channel, but it also affects the stable/master channel.

![image](https://user-images.githubusercontent.com/14216632/36764399-8b3ae7a8-1c80-11e8-9d2c-dda509fc69f3.png)

**Comment by badanka** [comment]
I tried a few games but I can't reproduce this. So I am going to need more information. Let's start with the basics:

- Which OS are you using? x86 or x64?
- What games are you seeing this behaviour with?
- Which Steam windows do you have open in the background? Does it matter?
- Do you run the games in fullscreen, windowed or borderless window? Does it matter?

That it would be a recent development with the stable channel makes me suspect that it might be related something else, since that hasn't been updated since December. I guess they could've done some changes to the backend, but I can't see it on my PC.

**Comment by ssolidus** [comment]
>Which OS are you using? x86 or x64?

x64

>What games are you seeing this behaviour with?

Every game I think, including **Dark Souls III** and **Kingdom Come: Deliverance**

>Which Steam windows do you have open in the background? Does it matter?

Even when I close all of them it still happens

>Do you run the games in fullscreen, windowed or borderless window? Does it matter?

Windowed mainly, but it doesn't matter - it always has high/spiked CPU usage.

**Comment by badanka** [comment]
I still would want to know which OS you're using.

I've tried 7 different games (I don't own the ones you brought up as examples) in both stable and beta channel now and I can't get my CPU usage for the Steam process to exceed 1% in any of those scenarios on my Windows 10 x64 PC. I'll test on my TabProS later when I've charged it and found some games that that thing can even run, just to be sure. 

My guess is that you have something in your setup that I lack which interferes with Steam somehow. Especially if it started just recently for you. Maybe some overly aggressive antivirus software? Regardless, I need either more reports from other users or a narrowed-down description to even begin searching for any faults with my skin. If I can't reproduce it I can't troubleshoot it. Sorry.

**Comment by ssolidus** [comment]
@badanka I am using Windows 7. I also tried disabling my antivirus

**Comment by badanka** [comment]
Any change for you or do you still have trouble?

**Comment by ssolidus** [comment]
Hey mate, I stopped using it because I didn't have time to fiddle with it. I'll try it again on the newest version  tonight and see how it goes.

I've used this theme for like 5 or 6 years so I don't wanna stop, but it hits game performance pretty hard - I was pretty sure its the themes fault as I noticed bugs reporting this in the past, making it really likely it is a bug regression.

**Comment by ssolidus** [comment]
Hey @badanka, I tried it again with the most recent Steam beta and it seems to be fine :)
