### ISSUE TITLE
Window buttons are compressed

### ISSUE THREAD

**Issue by HairyMilkshakes** [badanka/Compact#35]
Hi, been getting this issue lately with the latest Steam official build:

![2018-03-24_11-58-00](https://user-images.githubusercontent.com/13473043/37867810-ba09436c-2f5a-11e8-84a5-2a59453ecdb4.png)

Is it something on my end?

**Comment by badanka** [comment]
It's something that started with the latest Steam update. I have a fix coming soon, I'm just trying to go through all other kinds of window dialogs I can think of to see whether something else has popped up that I need to fix before pushing out an entirely new release. While you wait for that you can resize the window and the buttons will go back to normal.

**Comment by badanka** [comment]
Fixed in 1.6.04.
