### ISSUE TITLE
Interface glitch

### ISSUE THREAD

**Issue by julesCx** [badanka/Compact#36]
I started having this issue very recently ( http://prntscr.com/j65x8h ), i updated the version to see if it would work, but nothing. I switched back to the default steam skin and everything looked fine.
In-game overlay with the skin works fine too, and if i put my mouse on the boxes they appear again.

More screenshots:
http://prntscr.com/j65yrm
http://prntscr.com/j65zdi

**Comment by badanka** [comment]
Which version of Steam are you using, stable or beta? They released a beta update that was related to fixing this in particular just a few hours ago. And I'm currently not aiming for compatibility with beta versions.
If it's not a beta issue I need to know what OS you're on and if it happens both in maximised and in "restored" state.

**Comment by badanka** [comment]
Since there has been a week without any more comments, I'm deeming this invalid and will also close it.
