### ISSUE TITLE
Needs to be updated for the new chat room design

### ISSUE THREAD

**Issue by starkgate** [badanka/Compact#38]
Recent Steam update broke the skin, pretty much.

**Comment by ghost** [comment]
Well, it mostly works now with https://github.com/badanka/Compact/releases/tag/1.6.30, but I admit the clashing UI at the moment is somewhat amusing:

![img](https://xnaas.info/img/KosherOldImpala.png)

**Comment by badanka** [comment]
CreeperLava : It has been updated with 1.6.30.

xnaas: Thanks for stating the obvious. My first priority has been to get a working version out (I got one out within 22 hours even). I'm well aware that more work needs to be done to adapt to Steam's new Uplay appearance.

**Comment by ghost** [comment]
Try not to take offense where none is being given.

I look forward to the full compact experience in time.

**Comment by starkgate** [comment]
Thank you for the quick update ! No offense meant here either, I appreciate your work.
