### ISSUE TITLE
Misplaced Steam VR button.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [badanka/Compact#39]
[Like you can see on this screenshot](https://lewd.pics/p/?i=RErP.png), It would need to be adapted a bit. Since being, in a higher than the Big Picture button.

**Comment by badanka** [comment]
Try replacing your _steam\skins\Compact\resource\layout\steamrootdialog.layout_ file with [this one](https://github.com/badanka/Compact/blob/master/resource/layout/steamrootdialog.layout) and restart Steam.

I don't own a HMD so there's no way for me to get that button to show.

**Comment by PoorPocketsMcNewHold** [comment]
[Looking perfect!](https://lewd.pics/p/?i=TzQ4.png) Thanks for the rapid response, I'm closing this issue.
