### ISSUE TITLE
Skin updating the Installed/not installed grid picture only on hover.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [badanka/Compact#40]
[As displayed on this video](https://horobox.co.uk/u/nltfDw.mp4), The skin seems to only display which game I didn't installed, only when I hover them. This might be due to a big games library _(Far from bragging myself about it, but I've had 469 games in my library when I've done this video to show this issue)_

**Comment by badanka** [comment]
I'm getting the same issue on my end. I used a weird workaround made by someone else to even get this shading back into the skin once upon a time, so I guess it was just a matter of time before it broke. I'll look into whether I can find a solution and will report back here.
