### ISSUE TITLE
Plans for new Steam chat

### ISSUE THREAD

**Issue by ssolidus** [badanka/Compact#42]
As I am sure you are aware, the new Steam chat's UI is not managed locally by Steam, as it is a webapp. 

Do you have any plans to develop a Compact-like CSS file into the new chat?

**Comment by badanka** [comment]
Is there support for that? I know there's some kind of way to do some modifications to BPM through CSS, but I haven't really explored that anything at all so far. I'm guessing it would require replacing original files? I don't know much about it and I'm not really that well-versed in CSS either for that matter, but if it there's a feasible workaround and not too much of a headache to maintain I could probably consider it.

**Comment by ssolidus** [comment]
You can open the developer console in the chat by using CTRL + right-click, or CTRL+Shift+I. I think you might need the `-dev` or `-developer` executable flags for that, but I'm not sure.

The CSS files are located on `https://steamloopback.host/css/`, which indicates that it is hosting them on a mini-server on your PCs loopback address locally:
![image](https://user-images.githubusercontent.com/14216632/43356972-65e980b4-92bd-11e8-8710-4f5ea465a6fd.png)

If you check out `index_friends.html`, yo ucan see all the files used are hosted in this location - for all the dynamic data required, API calls are made to the external `https://steam-chat.com`. This would indicate it has been engineered to be modified.

It would appear all the variables of interest are stored in `shared_application.css` and `shared_dialog.css`. You know your theme better than I do, but based on this research I think it is feasible and not difficult to maintain.

**Comment by badanka** [comment]
Alright, but the more important question is, can you change any settings and avoid having them being overwritten by the client whenever its restarts/updates/decides to just verify its own files?

**Comment by bykidi** [comment]
@ssolidus please check steamservice.exe /repair

**Comment by Strappazzon** [comment]
> can you change any settings and avoid having them being overwritten by the client whenever its restarts/updates/decides to just verify its own files?

`-noverifyfiles` will prevent that
https://developer.valvesoftware.com/wiki/Command_Line_Options#Steam_.28Windows.29

**Comment by ghost** [comment]
have plans?

**Comment by badanka** [comment]
Forcing everyone to disable the file verification completely doesn't seem like a good solution though. That feature definitely has its merits, and it would also be difficult to educate all the users on how to use that and what side effects that action would lead to. It would also lead to an awful lot of false error reports heading my way. We would need a more elegant solution. Or maybe more preferably, we all need to put more pressure on Valve in regards to fixing the design of the friends and chat UI. It's probably only a matter of time before all windows in the Steam client will be redesigned, so.
