### ISSUE TITLE
Shouldn't this be changed?

### ISSUE THREAD

**Issue by ghost** [badanka/Compact#44]
![image](https://user-images.githubusercontent.com/40145743/44302730-8ad90b00-a2f4-11e8-9c7a-42262745176f.png)
I'm not completely sure, but I do not think this fits the theme, or if it was changed at all. Can it be changed? (I'm rarely active on Github, so please note that if I forget to respond)

**Comment by PoorPocketsMcNewHold** [comment]
What are you specifically talking about? _Don't tell me you want to change the steam website css, even tho it can be done via a Steam skin, it's entirely not what this one aim to do._

**Comment by ghost** [comment]
I really don't know the first thing about making Steam skins. I just felt that this didn't match and thought I'd say something in the case it was an issue.

**Comment by PoorPocketsMcNewHold** [comment]
Then, in this case, [Try to modify the compact skin with this one](https://steamcommunity.com/sharedfiles/filedetails/?id=442092873), as it's darker & compact look should make it more like the skin in itself. Here's how it look in a desktop view (Ignore all of my add-ons/scripts) 
![image](https://user-images.githubusercontent.com/13170204/44338986-fc919000-a47f-11e8-8e2b-70d60ac4ec65.png)
