### ISSUE TITLE
Music Details View only shows up to 14 songs for each album.

### ISSUE THREAD

**Issue by Mah0uPh0x** [badanka/Compact#46]
Albums in the Music Details view only show up to 14 songs, this also happens in the steam overlay.
![2019-09-29](https://user-images.githubusercontent.com/41488068/65838883-a8d5b500-e2d5-11e9-9a51-61086e79c18a.png)
My Sonic Mania album has 26 tracks, but the skin only shows 14 of them. This does not happen with the default skin.

**Comment by badanka** [comment]
Thanks for the report, I'll look into it.

**Comment by badanka** [comment]
This should be fixed with 1.6.52, sorry that you had wait this long.

**Comment by Mah0uPh0x** [comment]
Thank you very much!
