### ISSUE TITLE
Rivals of Aether (and possibly other games) freezes the Steam client completely when selected in Library in Details view

### ISSUE THREAD

**Issue by DessertArbiter** [badanka/Compact#47]
really strange that it seems to only happen with this one game on the Details layout in Library. im thinking it has something to do with the workshop display but im not sure why it only happens with this game. i have to end the task in task manager and open steam again but the same thing happens every time

**Comment by badanka** [comment]
I'm going to need more to go on for this one. What's special about the Workshop list for this particular game that makes you suspect that? Are you using Windows or Linux? You don't have any issues while using list or grid view?

**Comment by DessertArbiter** [comment]
windows 10, latest version 18362.418
it works fine in list and grid view, so i guess it could also be the achievements display that is causing the freeze
