### ISSUE TITLE
Needs an update after Steam patch.

### ISSUE THREAD

**Issue by x33st0rm** [badanka/Compact#48]
Steam went "big and useless", need my favorite skin to remedy this.

**Comment by janoi152** [comment]
Exactly. Steam client got really bad and useless recently and it's completely incompatible with Compact skin (except in steam://open/minigameslist mode where it still works).

**Comment by ThomasWeber** [comment]
You might consider using PlayNite instead. https://github.com/JosefNemec/Playnite

**Comment by EepyNewt** [comment]
I believe we have the same issues as #42 you can edit the css but steam reverts changes on restart so there's no official way to skin the new UI, only thing you can do with the steam client is the mini games list, or downgrade <https://youtu.be/bjN6-e3nlPE>

**Comment by Jonius7** [comment]
> but steam reverts changes on restart

Not if the original css file length stays the same.
https://github.com/Jonius7/SteamUI-OldGlory

**Comment by xnaas** [comment]
> Exactly. Steam client got really bad and useless recently and it's completely incompatible with Compact skin (except in steam://open/minigameslist mode where it still works).

Wow, thanks for this @janoi152! I can't believe I never knew this view existed.

For most Windows users the solution to always launch Steam this way:

1. Go to `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Steam`
2. Edit the Steam shortcut and add ` -minigameslist` to the `Target` field (outside of the quotes)
3. Apple and OK

Now Steam should always launch this way when pulling it up via the Start menu. If you launch Steam another way...glhf. 😛
