### ISSUE TITLE
Barely working

### ISSUE THREAD

**Issue by xeruf** [badanka/Compact#49]
I am on Arch Linux, followed all install instructions but it only really modifies the navigation at the top :/

**Comment by badanka** [comment]
I haven't tried it on Linux for quite some time now. I can't really modify the Friends list, Library or Downloads view with a regular skin anymore though. Is that what you're referring to? Or can you give me something more to go on?

**Comment by xeruf** [comment]
well, what does it modify then? the screenshots on https://badanka.github.io/Compact/ clearly show modifications to the Library.

**Comment by EepyNewt** [comment]
Old I know but to maybe close this...
this skin is in the official steam skins format, with the new UI for friends and library and such steam no longer lets skins modify it.
The screenshot was pre friends update

There is a tool called steam friends patcher that lets you modify it I believe, but I think you have to reapply your edits every update, and they have to be designed for that format not the old official skins one
