### ISSUE TITLE
Missing Navigation Bar in Steam Stable Build: Jan 31 2023, 11:07:35 (ver. 1675222618)

### ISSUE THREAD

**Issue by sthellen** [badanka/Compact#50]
Currently the navigation bar (Store, Library, Community, Profile) has been hidden or moved out of view in the latest steam beta version. Only the big picture mode can be interacted under the minimize and close window buttons.

~~The navigation bar is still present in the stable version from Dec 15 2022, 13:30:07 (ver. 1671236931).~~

# This is now affecting the current stable build of Steam (non-beta) from Jan 31 2023, 11:07:35 (ver. 1675222618).

![nonav](https://user-images.githubusercontent.com/4469038/211179458-7c0ed9db-581a-435d-a15e-6a88ab3a7967.jpg)
![steambetaver](https://user-images.githubusercontent.com/4469038/211179486-64aef9d4-866c-4442-8f46-801c43fdf59a.jpg)

**Comment by badanka** [comment]
[Should be fixed now, I just released 1.6.70.](https://github.com/badanka/Compact/releases/tag/1.6.70)
