### ISSUE TITLE
New Steam update broke the UI

### ISSUE THREAD

**Issue by HairyMilkshakes** [badanka/Compact#51]
After today's update.

**Comment by Painkiller998** [comment]
x2 :C

**Comment by SudosFTW** [comment]
This issue is a duplicate of #50 but now on release and not beta.

**Comment by HairyMilkshakes** [comment]
> This issue is a duplicate of #50 but now on release and not beta.

Thanks for letting me know I'll check it out.

**Comment by HairyMilkshakes** [comment]
A fix was posted here: https://github.com/sthellen/Compact/ but seems to be broken again by yet another update today.

**Comment by badanka** [comment]
[Should be fixed now, I just released 1.6.70.](https://github.com/badanka/Compact/releases/tag/1.6.70)
